export const callNYCCitationOrder = [
  "EVID-CALL-CIVICHALL-DATE",
  "EVID-CALL-NYCCOUNCIL-VENUE",
  "EVID-CALL-CIVICHALL-HOURS",
  "EVID-CALL-NYCCOUNCIL-FIRST-COUNCILSTAT",
  "EVID-CALL-PROMOTIONAL-BRANDING",
  "EVID-CALL-COUNCIL-DATA-PURPOSE",
  "EVID-CALL-POLITICO-INDEPENDENT-FOLLOW-ON",
  "EVID-CALL-POLITICO-LIMITATIONS",
  "EVID-CALL-POLITICO-COVERAGE",
  "EVID-CALL-GITHUB-REPOSITORY"
] as const;
