#!/usr/bin/env node
import { existsSync, lstatSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { buildMailReadings, renderMailPages, relative, hash, METHOD } from './core.mjs';

try {
  const args = process.argv.slice(2);
  let root, manifestPath, mode, requireComplete = false;
  for (let i = 0; i < args.length; i++) {
    if (args[i] === '--root') root = path.resolve(args[++i]);
    else if (args[i] === '--manifest') manifestPath = relative(args[++i]);
    else if (['--plan','--check','--write'].includes(args[i]) && !mode) mode = args[i];
    else if (args[i] === '--require-complete') requireComplete = true;
    else throw new Error('unknown-argument');
  }
  if (!root || !manifestPath || !mode) throw new Error('explicit-scope-required');
  function local(file) {
    relative(file);
    let current = root;
    for (const piece of file.split('/')) {
      current = path.join(current, piece);
      if (existsSync(current) && lstatSync(current).isSymbolicLink()) throw new Error('symlink-denied');
    }
    return current;
  }
  if (JSON.parse(readFileSync(local('config/paired-workspace.private.json'), 'utf8')).repository_visibility !== 'PRIVATE') throw new Error('private-root-required');
  const source = readFileSync(local(manifestPath), 'utf8');
  const manifest = JSON.parse(source);
  const result = buildMailReadings(manifest, file => readFileSync(local(file), 'utf8'));
  const pages = renderMailPages(manifest, result);
  const implementation = ['cli.mjs','core.mjs'].map(f => hash(readFileSync(fileURLToPath(new URL(f, import.meta.url))))).join(':');
  const receipt = { ...result, manifest_sha256: hash(source), implementation_sha256: hash(implementation), pages_sha256: hash(JSON.stringify(pages)) };
  pages[`${manifest.output_dir}/projection.json`] = JSON.stringify(receipt, null, 2) + '\n';
  const output = local(manifest.output_dir);
  const extras = existsSync(output) ? readdirSync(output).filter(f => !Object.hasOwn(pages, `${manifest.output_dir}/${f}`)) : [];
  if (extras.length) throw new Error('unexpected-output-files-review-required');
  for (const [file] of Object.entries(pages)) {
    if (existsSync(local(file))) {
      const current = readFileSync(local(file), 'utf8');
      if (file.endsWith('.md') && !current.includes(`<!-- Generated by ${METHOD}.`) && mode === '--write') throw new Error('unmanaged-output-collision');
    }
  }
  const current = Object.entries(pages).every(([file, text]) => existsSync(local(file)) && readFileSync(local(file), 'utf8') === text);
  if (mode === '--write') {
    mkdirSync(output, { recursive: true });
    for (const [file, text] of Object.entries(pages)) writeFileSync(local(file), text);
  }
  process.stdout.write(JSON.stringify({ method: METHOD, message_count: result.message_count, entry_count: result.entry_count, candidate_count: result.candidate_count, complete: result.complete, human_review_complete: false,
    projection_current: mode === '--write' || current, manifest_sha256: receipt.manifest_sha256, implementation_sha256: receipt.implementation_sha256 }, null, 2) + '\n');
  process.exitCode = mode === '--check' && !current ? 1 : requireComplete && !result.complete ? 2 : 0;
} catch {
  // Source text, paths, URLs and account identities never enter public diagnostics.
  process.stderr.write('mail-workflow-invalid; inspect scoped private inputs and regression tests\n');
  process.exitCode = 1;
}
