import test from "node:test";
import assert from "node:assert/strict";
import * as fs from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";
import { execFileSync } from "node:child_process";
import { createHash, generateKeyPairSync, sign } from "node:crypto";
import { ledgerFingerprint } from "../rfcs/irl-changelog-eval.mjs";
import { planAppend, openStore, commitPlan, inspectStore, rollbackStore, createAdapter, projectView, planLegacy } from "./runtime.mjs";
import { runCLI } from "./cli.mjs";
const baseline=JSON.parse(fs.readFileSync(new URL("../../evals/knowledge-bank/irl-changelog-rfc-evals.json",import.meta.url))).baseline;
const sha=b=>createHash("sha256").update(b).digest("hex");
const now="2026-09-06T20:00:00Z";
const use={context:"synthetic:working",recipient:"actor:synthetic-operator",purpose:"working-understanding",transformation:"bounded-summary"};
function fixture(t) {
 const home=fs.mkdtempSync(path.join(tmpdir(),"irl-runtime-test-"));
 t.after(()=>fs.rmSync(home,{recursive:true}));
 const repo=path.join(home,"evidence"),store=path.join(home,"store");fs.mkdirSync(repo);
 const git=args=>execFileSync("git",args,{cwd:repo,stdio:["ignore","pipe","pipe"]}).toString().trim();
 git(["init","-q"]);git(["config","user.name","Synthetic fixture"]);git(["config","user.email","fixture@example.invalid"]);
 fs.writeFileSync(path.join(repo,"source.txt"),"Synthetic source passage.\n");git(["add","source.txt"]);git(["commit","-qm","Fixture"]);
 const record=structuredClone(baseline);record.sources[0].revision=git(["rev-parse","HEAD"]);record.sources[0].sha256=sha(fs.readFileSync(path.join(repo,"source.txt")));
 const {privateKey,publicKey}=generateKeyPairSync("ed25519");
 const s=record.sources[0], payload={receipt_id:"review:one",reviewed_by:"reviewer:fixture",decision:"permitted",source_revision:s.revision,source_sha256:s.sha256,source_flow:s.flow,use,valid_until:"2026-09-07T00:00:00Z"};
 const signed={key_id:"fixture",payload,signature:sign(null,Buffer.from(ledgerFingerprint(payload)),privateKey).toString("base64")};
 const config={scope:record.scope,store_root:store,write_enabled:true,checkpoint:{record,fingerprint:ledgerFingerprint(record)},
  entities:structuredClone(record.entities),sources:{[s.id]:{repo,path:"source.txt",revision:s.revision,sha256:s.sha256,read_allowed:true,eligibility:"permitted"}},
  review_keys:{fixture:{public_key:publicKey.export({type:"spki",format:"pem"}),reviewer:"reviewer:fixture"}},
  context_heads:{[s.id]:ledgerFingerprint(signed)},context_reviews:{[s.id]:signed}};
 const trust=()=>createAdapter(config,{expectedDigest:ledgerFingerprint(config),now:()=>now});
 const input={entries:[{...structuredClone(record.entries[0]),id:"change:next",recorded_at:undefined,learned_on:"2026-09-06",now:"A later interpretation."}],sources:[],entities:[],views:[{id:"subject",entity_ids:["entity:example-project"],use}]};
 return {home,repo,store,record,config,trust,input,privateKey};
}
const plan=f=>planAppend(f.record,f.input,{expectedPrior:ledgerFingerprint(f.record),idempotencyKey:"append-one",now:()=>now});
const boot=f=>openStore({root:f.store,adapter:f.trust()});
test("rollback disables the consumer as well as future writes",t=>{const f=fixture(t),first=boot(f);const next=commitPlan({root:f.store,plan:plan(f),adapter:f.trust()});rollbackStore({root:f.store,adapter:f.trust(),expectedGeneration:next.generation,targetGeneration:first.generation,reason:"Recovery"});assert.equal(inspectStore({root:f.store,adapter:f.trust()}).consumer_enabled,false);});
test("legacy CLI rejects an unverified snapshot hash without writing",t=>{const f=fixture(t);const p=path.join(f.home,"legacy.json");fs.writeFileSync(p,JSON.stringify({schema_version:1,entries:[],sources:[]}));assert.throws(()=>runCLI(["legacy-plan","--legacy",p,"--revision","a".repeat(40),"--sha256","b".repeat(64)]),/legacy-bytes/);assert.equal(fs.existsSync(f.store),false);});
const cliArgs=f=>{const config=path.join(f.home,"operator.json");fs.writeFileSync(config,JSON.stringify(f.config));return ["--policy",config,"--policy-digest",ledgerFingerprint(f.config)];};
test("CLI requires an independent policy digest before initialization",t=>{const f=fixture(t);assert.throws(()=>runCLI(["init","--policy",path.join(f.home,"unused.json")]),/policy-digest/);assert.equal(fs.existsSync(f.store),false);});
test("CLI initialization and inspection use the sealed runtime",t=>{const f=fixture(t),args=cliArgs(f);assert.equal(runCLI(["init",...args]).status,"initialized");assert.equal(runCLI(["inspect",...args]).integrity,"verified");});
test("CLI rejects unknown options without side effects",t=>{const f=fixture(t);assert.throws(()=>runCLI(["init",...cliArgs(f),"--publish","yes"]),/unknown-option/);assert.equal(fs.existsSync(f.store),false);});
test("CLI cannot take trust policy from its mutable store",t=>{const f=fixture(t);fs.mkdirSync(f.store,{mode:0o700});const p=path.join(f.store,"policy.json");fs.writeFileSync(p,JSON.stringify(f.config));assert.throws(()=>runCLI(["init","--policy",p,"--policy-digest",ledgerFingerprint(f.config)]),/policy-outside-store/);});
test("retry after later append returns its original generation",t=>{const f=fixture(t);boot(f);const original=plan(f),first=commitPlan({root:f.store,plan:original,adapter:f.trust()});const current=inspectStore({root:f.store,adapter:f.trust()}).record;f.input.entries[0].id="change:third";const second=planAppend(current,f.input,{expectedPrior:ledgerFingerprint(current),idempotencyKey:"append-two",now:()=>now});commitPlan({root:f.store,plan:second,adapter:f.trust()});assert.equal(commitPlan({root:f.store,plan:original,adapter:f.trust()}).generation,first.generation);});
test("pointer rewind leaves retained work and prevents new appends",t=>{const f=fixture(t);const first=boot(f);commitPlan({root:f.store,plan:plan(f),adapter:f.trust()});fs.writeFileSync(path.join(f.store,"CURRENT"),JSON.stringify({generation:first.generation,disabled:false}));assert.throws(()=>commitPlan({root:f.store,plan:plan(f),adapter:f.trust()}),/recovery-required/);});
test("planning stamps actual append time without changing prior history",t=>{
 const f=fixture(t),p=plan(f);
 assert.equal(p.record?.entries?.length,2);
 assert.deepEqual(p.record.entries[0],f.record.entries[0]);
 assert.equal(p.record.entries[1].recorded_at,now);
 assert.equal(p.record.entries[1].id,"change:next");
});
test("stale expected prior cannot plan an append",t=>{const f=fixture(t);assert.throws(()=>planAppend(f.record,f.input,{expectedPrior:"0".repeat(64),idempotencyKey:"k",now:()=>now}),/stale/);});
test("retry keys are required",t=>{const f=fixture(t);assert.throws(()=>planAppend(f.record,f.input,{expectedPrior:ledgerFingerprint(f.record),now:()=>now}),/idempotency/);});
test("an entry cannot smuggle append time through authored fields",t=>{const f=fixture(t);f.input.entries[0].recorded_at="2001-01-01T00:00:00Z";assert.throws(()=>plan(f),/recorded-at/);});
test("unknown learning is retained rather than filled from append time",t=>{const f=fixture(t);f.input.entries[0].learned_on=null;f.input.entries[0].learning_time_reason="Observer receipt time was not recorded.";assert.equal(plan(f).record?.entries?.[1].learned_on,null);});
test("authority in authored ledger does not enable writes",t=>{const f=fixture(t);f.config.write_enabled=false;assert.throws(()=>boot(f),/write-disabled/);assert.equal(fs.existsSync(path.join(f.store,"CURRENT")),false);});
test("operator policy digest cannot be replaced by an authored declaration",t=>{const f=fixture(t);assert.throws(()=>createAdapter(f.config,{expectedDigest:"0".repeat(64)}),/trust-digest/);});
test("checkpoint fingerprint is verified independently of working ledger",t=>{const f=fixture(t);f.config.checkpoint.record.entries[0].now="Rewritten";assert.throws(()=>boot(f),/checkpoint/);});
test("initialize and append commit one sealed generation",t=>{const f=fixture(t);boot(f);const result=commitPlan({root:f.store,plan:plan(f),adapter:f.trust()});assert.equal(result.status,"committed");const read=inspectStore({root:f.store,adapter:f.trust()});assert.equal(read.record?.entries?.length,2);assert.equal(read.integrity,"verified");assert.equal(read.publication_authorized,false);});
test("stale writer cannot overwrite an accepted concurrent append",t=>{const f=fixture(t);boot(f);const p=plan(f);commitPlan({root:f.store,plan:p,adapter:f.trust()});p.idempotency_key="other";assert.throws(()=>commitPlan({root:f.store,plan:p,adapter:f.trust()}),/stale/);});
test("retry returns the same generation, not a duplicate entry",t=>{const f=fixture(t);boot(f);const p=plan(f),a=commitPlan({root:f.store,plan:p,adapter:f.trust()}),b=commitPlan({root:f.store,plan:p,adapter:f.trust()});assert.equal(b.status,"idempotent");assert.equal(b.generation,a.generation);assert.equal(inspectStore({root:f.store,adapter:f.trust()}).record?.entries?.length,2);});
test("same retry key with different content conflicts",t=>{const f=fixture(t);boot(f);const p=plan(f);commitPlan({root:f.store,plan:p,adapter:f.trust()});f.input.entries[0].now="Different request";assert.throws(()=>commitPlan({root:f.store,plan:plan(f),adapter:f.trust()}),/idempotency-conflict/);});
test("rewriting old entry fails even when caller changes its expected hash",t=>{const f=fixture(t);boot(f);const p=plan(f);p.record.entries[0].now="Silent rewrite";assert.throws(()=>commitPlan({root:f.store,plan:p,adapter:f.trust()}),/history|plan-digest/);});
test("manual edits are retained and prevent further writes",t=>{const f=fixture(t);const opened=boot(f);const target=path.join(f.store,"generations",opened.generation,"history.md");fs.appendFileSync(target,"\nHuman note\n");assert.throws(()=>commitPlan({root:f.store,plan:plan(f),adapter:f.trust()}),/integrity/);assert.ok(fs.readFileSync(target,"utf8").endsWith("Human note\n"));});
test("held source cannot be opened by the trusted adapter",t=>{const f=fixture(t);f.config.sources[f.record.sources[0].id].read_allowed=false;const result=projectView(f.record,{id:"subject",entity_ids:["entity:example-project"],use},f.trust());assert.equal(result.status,"hold");assert.ok(result.reasons?.includes("source-unavailable-or-restricted"));});
test("real source bytes must match the recorded Git pin",t=>{const f=fixture(t),changed=structuredClone(f.record);changed.sources[0].sha256="a".repeat(64);assert.equal(projectView(changed,{id:"s",entity_ids:["entity:example-project"],use},f.trust()).status,"hold");});
test("claimed resolved identity must match an independent registry",t=>{const f=fixture(t);f.config.entities=[];assert.equal(projectView(f.record,{id:"s",entity_ids:["entity:example-project"],use},f.trust()).status,"hold");});
test("a verified source and signed current contextual review yield only a candidate",t=>{const f=fixture(t);const r=projectView(f.record,{id:"s",entity_ids:["entity:example-project"],use},f.trust());assert.equal(r.status,"current-candidate");assert.equal(r.human_review_complete,false);assert.equal(r.publication_authorized,false);});
test("unsigned permitted review is not trusted",t=>{const f=fixture(t);f.config.context_reviews[f.record.sources[0].id].signature="";assert.equal(projectView(f.record,{id:"s",entity_ids:["entity:example-project"],use},f.trust()).status,"hold");});
test("revoked current review cannot fall back to an older permitted one",t=>{const f=fixture(t);f.config.context_heads[f.record.sources[0].id]="0".repeat(64);assert.equal(projectView(f.record,{id:"s",entity_ids:["entity:example-project"],use},f.trust()).status,"hold");});
test("a changed recipient cannot reuse a valid signature",t=>{const f=fixture(t);assert.equal(projectView(f.record,{id:"s",entity_ids:["entity:example-project"],use:{...use,recipient:"actor:other"}},f.trust()).status,"hold");});
test("expired review is held",t=>{const f=fixture(t);const adapter=createAdapter(f.config,{expectedDigest:ledgerFingerprint(f.config),now:()=>"2026-09-08T00:00:00Z"});assert.equal(projectView(f.record,{id:"s",entity_ids:["entity:example-project"],use},adapter).status,"hold");});
test("fixed-point correction basis preserves both sides across subjects",t=>{const f=fixture(t),r=structuredClone(f.record);r.entities.push({id:"entity:other",type:"project",resolution:"resolved"});f.config.entities=r.entities;r.entries.push({...structuredClone(r.entries[0]),id:"change:correction",kind:"correction",recorded_at:"2020-01-07T12:00:00Z",about:[{id:"entity:other",type:"project"}],corrections:[{entry_id:r.entries[0].id,field:"now",reason:"Later evidence."}]});const result=projectView(r,{id:"s",entity_ids:["entity:other"],use},f.trust());assert.deepEqual(result.basis_entry_ids,["change:example-a","change:correction"]);});
test("unrelated unknown learning does not hide a supported view",t=>{const f=fixture(t),r=structuredClone(f.record);r.entities.push({id:"entity:other",type:"project",resolution:"unresolved"});r.entries.push({...structuredClone(r.entries[0]),id:"change:held",learned_on:null,learning_time_reason:"Unknown",about:[{id:"entity:other",type:"project"}]});assert.equal(projectView(r,{id:"s",entity_ids:["entity:example-project"],use},f.trust()).status,"current-candidate");});
test("a held correction cannot be omitted to make its target look current",t=>{const f=fixture(t),r=plan(f).record;r.entries[1].kind="correction";r.entries[1].corrections=[{entry_id:r.entries[0].id,field:"now",reason:"Later evidence."}];r.entries[1].learned_on=null;r.entries[1].learning_time_reason="Unknown";assert.equal(projectView(r,{id:"s",entity_ids:["entity:example-project"],use},f.trust()).status,"hold");});
test("writer lock cannot be silently broken",t=>{const f=fixture(t);boot(f);fs.mkdirSync(path.join(f.store,".writer-lock"));assert.throws(()=>commitPlan({root:f.store,plan:plan(f),adapter:f.trust()}),/locked/);});
test("failure before CURRENT switch leaves previous generation readable",t=>{const f=fixture(t);const first=boot(f),io={...fs,renameSync:(from,to)=>{if(to===path.join(f.store,"CURRENT"))throw Error("simulated I/O");fs.renameSync(from,to);}};assert.throws(()=>commitPlan({root:f.store,plan:plan(f),adapter:f.trust(),io}),/simulated I\/O/);const read=inspectStore({root:f.store,adapter:f.trust()});assert.equal(read.generation,first.generation);assert.equal(read.record.entries.length,1);assert.ok(read.recovery.orphans.length>0);});
test("rollback retains new generation and disables fresh writes pending reconciliation",t=>{const f=fixture(t),first=boot(f),next=commitPlan({root:f.store,plan:plan(f),adapter:f.trust()});const result=rollbackStore({root:f.store,adapter:f.trust(),expectedGeneration:next.generation,targetGeneration:first.generation,reason:"Operator recovery test"});assert.equal(result.status,"rolled-back-held");assert.ok(fs.existsSync(path.join(f.store,"generations",next.generation)));assert.throws(()=>commitPlan({root:f.store,plan:plan(f),adapter:f.trust()}),/disabled/);});
test("symlink store escapes are rejected",t=>{const f=fixture(t);fs.mkdirSync(path.join(f.home,"elsewhere"));fs.symlinkSync(path.join(f.home,"elsewhere"),f.store);assert.throws(()=>boot(f),/symlink/);});
test("saved views are rechecked after source revocation",t=>{const f=fixture(t);boot(f);commitPlan({root:f.store,plan:plan(f),adapter:f.trust()});f.config.sources[f.record.sources[0].id].read_allowed=false;const r=inspectStore({root:f.store,adapter:f.trust()});assert.equal(r.views[0].status,"hold");assert.equal(r.views[0].reading,null);});
test("a dangling symlink cannot be used as the store root",t=>{const f=fixture(t);fs.symlinkSync(path.join(f.home,"absent"),f.store);assert.throws(()=>boot(f),/symlink/);});
test("open permissions on an existing store are rejected",t=>{const f=fixture(t);fs.mkdirSync(f.store,{mode:0o755});assert.throws(()=>boot(f),/private-permissions/);});
test("duplicate stable ids fail planning",t=>{const f=fixture(t);f.input.entries[0].id=f.record.entries[0].id;assert.throws(()=>plan(f),/duplicate-id/);});
test("a plan made earlier gets its actual append timestamp at commit",t=>{const f=fixture(t);boot(f);const adapter=createAdapter(f.config,{expectedDigest:ledgerFingerprint(f.config),now:()=>"2026-09-06T20:05:00Z"});commitPlan({root:f.store,plan:plan(f),adapter});assert.equal(inspectStore({root:f.store,adapter}).record.entries[1].recorded_at,"2026-09-06T20:05:00Z");});
test("Git working-copy edits cannot replace the cited immutable blob",t=>{const f=fixture(t);fs.writeFileSync(path.join(f.repo,"source.txt"),"Changed working copy");assert.equal(projectView(f.record,{id:"s",entity_ids:["entity:example-project"],use},f.trust()).status,"current-candidate");});
test("current revoked permission overrides a correctly signed old permit",t=>{const f=fixture(t);const s=f.record.sources[0];f.config.sources[s.id].eligibility="revoked";assert.equal(projectView(f.record,{id:"s",entity_ids:["entity:example-project"],use},f.trust()).status,"hold");});
test("a forged receipt cannot be blessed by replacing its declared head",t=>{const f=fixture(t);const s=f.record.sources[0],receipt=f.config.context_reviews[s.id];receipt.payload.use.recipient="actor:forged";f.config.context_heads[s.id]=ledgerFingerprint(receipt);assert.equal(projectView(f.record,{id:"s",entity_ids:["entity:example-project"],use:receipt.payload.use},f.trust()).status,"hold");});
test("legacy planning preserves ids, observation dates and explicit unknowns without applying migration",()=>{
 const old={schema_version:1,entries:[{id:"IRL-0001",observed_on:"2020-01-02",now:"Legacy understanding",entities:["private:person.example"],evidence:[]}],sources:[{id:"s",sha256:"a".repeat(64)}]};
 const before=JSON.stringify(old),p=planLegacy(old,{revision:"b".repeat(40),sha256:sha(before)});
 assert.equal(p.status,"migration-plan-held");assert.equal(p.entries?.[0].id,"IRL-0001");assert.equal(p.entries?.[0].observed_on,"2020-01-02");assert.equal(p.entries?.[0].learned_on,null);assert.equal(p.migration_applied,false);assert.equal(JSON.stringify(old),before);
});
